[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "4ZEmcaFaGibYfS26kNvvQm4EAiAgWCi4w3YQj4i2qp67"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-amm.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-pool.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/deposit-liquidity.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/withdraw-liquidity.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/swap.ts"