[toolchain]
solana_version = "2.1.0"  

[features]
seeds = false
skip-lint = false

[programs.devnet]
todo_app = "5qc4okxCxVSpm6B3Tp4QmHtuQV966Q4zZh4n87FL9mjS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/huygia/.config/solana/id.json" 

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-profile.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-todo.ts"
